//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSounds.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARSounds.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        public static string About_application {
            get {
                return ResourceManager.GetString("About_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application provides a customizable dashboard environment, allowing users to visualize, manage, and interact with data dynamically. With a focus on data presentation and analytics, it enables users to create structured pages containing various visualization elements such as charts, tables, and statistics..
        /// </summary>
        public static string About_application_description {
            get {
                return ResourceManager.GetString("About_application_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings.
        /// </summary>
        public static string Account_settings {
            get {
                return ResourceManager.GetString("Account_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string Add_account {
            get {
                return ResourceManager.GetString("Add_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARSounds.
        /// </summary>
        public static string Application_title {
            get {
                return ResourceManager.GetString("Application_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARSounds account.
        /// </summary>
        public static string ARSounds_account {
            get {
                return ResourceManager.GetString("ARSounds_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message.
        /// </summary>
        public static string Exception_message {
            get {
                return ResourceManager.GetString("Exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Personalization {
            get {
                return ResourceManager.GetString("Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string Privacy_terms_link {
            get {
                return ResourceManager.GetString("Privacy_terms_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://YourPrivacyUrlGoesHere/.
        /// </summary>
        public static string Privacy_terms_link_navigate_uri {
            get {
                return ResourceManager.GetString("Privacy_terms_link_navigate_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        public static string Stack_Trace {
            get {
                return ResourceManager.GetString("Stack_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Theme.
        /// </summary>
        public static string System_theme {
            get {
                return ResourceManager.GetString("System_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Tour.
        /// </summary>
        public static string Take_tour {
            get {
                return ResourceManager.GetString("Take_tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        public static string Unhandled_exception {
            get {
                return ResourceManager.GetString("Unhandled_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To a new world of possibilities,
        ///welcome to ARSounds..
        /// </summary>
        public static string Walkthrough_subtitle_step_1 {
            get {
                return ResourceManager.GetString("Walkthrough_subtitle_step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save countless hours of UI Design.
        ///Focus on what you do best..
        /// </summary>
        public static string Walkthrough_subtitle_step_2 {
            get {
                return ResourceManager.GetString("Walkthrough_subtitle_step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn while you do. 
        ///MAUI Kit has ton of examples for you to play..
        /// </summary>
        public static string Walkthrough_subtitle_step_3 {
            get {
                return ResourceManager.GetString("Walkthrough_subtitle_step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Walkthrough_title_step_1 {
            get {
                return ResourceManager.GetString("Walkthrough_title_step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Time.
        /// </summary>
        public static string Walkthrough_title_step_2 {
            get {
                return ResourceManager.GetString("Walkthrough_title_step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        public static string Walkthrough_title_step_3 {
            get {
                return ResourceManager.GetString("Walkthrough_title_step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take your App to the next level with MAUI Kit..
        /// </summary>
        public static string Welcome_subtitle {
            get {
                return ResourceManager.GetString("Welcome_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready made UI&apos;s for .NET MAUI and Xamarin.Forms..
        /// </summary>
        public static string Welcome_title {
            get {
                return ResourceManager.GetString("Welcome_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Default.
        /// </summary>
        public static string Windows_default {
            get {
                return ResourceManager.GetString("Windows_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
