// <auto-generated />
using System;
using ARSounds.Server.EntityFramework.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARSounds.Web.Api.EntityFramework.MySql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240713203122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ARSounds.Web.Api.EntityFramework.Entities.Audio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("AudioBytes")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("AudioType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Audio");
                });

            modelBuilder.Entity("ARSounds.Web.Api.EntityFramework.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Buffer")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("VisionTargetId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ARSounds.Web.Api.EntityFramework.Entities.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AudioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrackable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AudioId")
                        .IsUnique();

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("Target");
                });

            modelBuilder.Entity("ARSounds.Web.Api.EntityFramework.Entities.Target", b =>
                {
                    b.HasOne("ARSounds.Web.Api.EntityFramework.Entities.Audio", "Audio")
                        .WithOne("Target")
                        .HasForeignKey("ARSounds.Web.Api.EntityFramework.Entities.Target", "AudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ARSounds.Web.Api.EntityFramework.Entities.Image", "Image")
                        .WithOne("Target")
                        .HasForeignKey("ARSounds.Web.Api.EntityFramework.Entities.Target", "ImageId");

                    b.Navigation("Audio");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ARSounds.Web.Api.EntityFramework.Entities.Audio", b =>
                {
                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("ARSounds.Web.Api.EntityFramework.Entities.Image", b =>
                {
                    b.Navigation("Target")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
